[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = [
  "rm -rf dist node_modules/.vite",
  "npm run build",
  "cp serve.json dist/"
]

[start]
cmd = "cd dist && npx serve -s -l $PORT"

[variables]
NPM_CONFIG_PRODUCTION = "false"
