[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = [
  "rm -rf dist node_modules/.vite",
  "npm run build"
]

[start]
cmd = "npx serve dist -s -l $PORT"

[variables]
NPM_CONFIG_PRODUCTION = "false"
